#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 25 06:52:54 2022

@author: truscottwatters
"""

from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as ss
import random 
import pandas as pd

def f(x):
    return np.sin(x) / 55 + np.cos(x) / 13
def main():
    plt.figure(0, dpi=200, figsize=[10, 5])
    plt.title("Polynomial Interpolation Artificial Intelligence Prediction. Charles Truscott Watters")
    random.seed(1)
    x = np.linspace(0, 10, 100)
    y = f(x)
    X = x[:,np.newaxis]
    X_plot = X
    colors=['black', 'grey', 'purple']
    plt.plot(X_plot, y, color='gold', label="sin(x) over 55 plus cos(x) over 13")
    for count, degree in enumerate([2, 3, 4]):
        model = make_pipeline(PolynomialFeatures(degree), Ridge())
        model.fit(X, y)
        y_plot = model.predict(X_plot)
        plt.plot(X_plot, y_plot, color=colors[count], label="degree {} Artificial Intelligence polynomial fit of the function sin(x) over 55 plus cos(x) over 13".format(degree))
    plt.legend()
    plt.xlabel("x. Thank you Harvard University and JP Onnela")
    plt.ylabel("y equals sin(x) / 55 plus cos(x) / 13")
    plt.show()
if __name__ == "__main__": main()